"""m

Revision ID: 0b230169b59f
Revises: 
Create Date: 2023-05-21 12:41:59.800046

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b230169b59f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "reembolsado", "aprovado", "recusado", name="paymentstatusconstraint"
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.Column("payment_method", sa.String(length=100), nullable=False),
        sa.Column("installments", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "access_released",
                "access_revoked",
                "welcome_message",
                "payment_declined_message",
                "refund_message",
                name="actionconstraint",
            ),
            nullable=False,
        ),
        sa.Column("action_time", sa.DateTime(), nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_actions")
    op.drop_table("webhooks")
    op.drop_table("users")
    # ### end Alembic commands ###
